### ISSUE TITLE
1600 calibration parameter

### ISSUE THREAD

**Issue by evteevakb** [LaboratoireMecaniqueLille/Seek-thermal-Python#1]
Hello! I have one question regarding camera calibration: as I see in the row number 164 (get_image method) , you use the following calculation:
self.calib = self.crop(img)-1600
Could you please explain, what does 1600 mean? Is it a fixed parameter for all cameras or should I somehow change it?
Thanks in advance.

**Comment by Dad0u** [comment]
Hello,
This parameter was a dirty workaround : This code was developed in a rush and there is room for many improvements. Sadly i don't have the Seek thermal with me at the moment to work on it.
My understanding is that the "clean" image should be raw_image - calib_image, however doing this may induce and integer overflow as both inputs are uint16 and so is the result. You can try to remove this -1600 to see for yourself: the cold regions will be warped to dl values of 16384. A cleaner workaround would be to cast the result in uint32.

This value was added by trial and error, to avoid this warping effet. You should note that at this point, no connection is made between the digital level and the temperature.

I hope this answers your question

**Comment by evteevakb** [comment]
Thanks for the answer! I removed -1600 and got this problem with cold regions as you told (especially when I moved a view from cold to hot objects)
