### ISSUE TITLE
usb.core.USBError: [Errno 32] Pipe error

### ISSUE THREAD

**Issue by duydangg** [LaboratoireMecaniqueLille/Seek-thermal-Python#4]
can anyone help me with this problem when i ran python3 seekpro.py

**Comment by asmolinski** [comment]
Hi. You can try unplug, then plug your camera back.

This script doesnt include release device on exit, so windows blocked them after first use.

**Comment by WeisLeDocto** [comment]
Closing issue due to prolonged inactivity
