### ISSUE TITLE
Is there a way to change to other modes?

### ISSUE THREAD

**Issue by Miggiez** [LaboratoireMecaniqueLille/Seek-thermal-Python#6]
I was planning to create a project that will utilize the prism and spectra mode of the Seek Compact Pro. Is there a way to change the mode using this software?

**Comment by Dad0u** [comment]
No, this script is very basic and does provide functions to apply a colormap. 
If you want to apply a color map to the image, i can suggest cv2.applyColorMap or display it with matplotlib with plt.imshow(..., cmap="<your colormap>")
